#!/bin/bash

# make_fatpack - packs tools with dependencies.
#
# Makes autonomous (packed with dependencies) Perl scripts for the
# tools from ./bin with the fatpack utility (App::FatPacker) and
# puts them under ./fatpack.
#
# Copyright (c) 2011-2015 Sergey Konoplev

set -e

BIN_DIR="$(dirname $0)/bin"
FATPACK_DIR="$(dirname $0)/fatpack"
PERL='/usr/bin/perl'

# Fatpack the scripts
find $FATPACK_DIR -type f -delete
mkdir -p /tmp/pgtoolkit_fatlib
for script in $(ls -1 $BIN_DIR); do
    (echo "#!$PERL"; fatpack file; cat $BIN_DIR/$script) >$FATPACK_DIR/$script
    chmod 755 $FATPACK_DIR/$script
    echo $FATPACK_DIR/$script
done
rm -rf /tmp/pgtoolkit_fatlib
