#!/bin/bash
#
# The download files making script.
#
# The script makes two .tar.gz archives, one is for the autonomous
# Perl scripts built by the fatpack (App::FatPacker) tool and another
# is for the source files, and puts them into the destination
# directory.
#
# The TAG argument is required. The script is assumed to be run at the
# repository root.
#
# Copyright (c) 2012, PostgreSQL-Consulting.com
#
# Sergey Konoplev <sergey.konoplev@postgresql-consulting.com>

SRCDIR=bin
DESTDIR=files

scriptlist=$(ls -1 $SRCDIR)

if [ $# -eq 1 ]; then
    sourcecodetargz=pgtoolkit-$1-sourcecode.tar.gz
    fatscriptstargz=pgtoolkit-$1-fatscripts.tar.gz
    echo $DESTDIR/$fatscriptstargz
    echo $DESTDIR/$sourcecodetargz
else
    echo "Usage: make_files TAG" >&2
    exit 1
fi

test -e $DESTDIR || mkdir $DESTDIR

# Fatpack the scripts
mkdir fatlib
for script in $scriptlist; do
    (echo "#!/usr/bin/perl"; fatpack file; cat $SRCDIR/$script) \
	> $DESTDIR/$script 2> /dev/null
    chmod 755 $DESTDIR/$script
done
rm -rf fatlib

# Archive the fatpacked scripts and remove them
(
    cd $DESTDIR/
    tar -czf $fatscriptstargz $scriptlist
    rm $scriptlist
)

# Make the source code archive
tar --exclude .svn --exclude $DESTDIR -czf $DESTDIR/$sourcecodetargz .
